clueBank =[
{category:'Things in a Classroom' , clue:'rubber band'},
{category:'Movies' , clue:'let it go'},
{category:'Gifts' , clue:'friendship bracelet'},
{category:'Disney' , clue:'alice in wonderland'},
{category:'Books' , clue:'the cat in the hat'},
{category:'Books' , clue:'the cat in the hat'},
{category:'Movies' , clue:'charlotte’s web'},
{category:'Movies' , clue:'harry potter'},
{category:'Movies' , clue:'diary of a wimpy kid'},
{category:'Movies' , clue:'diary of a wimpy kid'},
{category:'Movies' , clue:'babe'},
{category:'Movies' , clue:'bambi'},
{category:'Movies' , clue:'frozen'},
{category:'Movies' , clue:'cats and dogs'},
{category:'Movies' , clue:'cinderella'},
{category:'Movies' , clue:'finding nemo'},
{category:'Movies' , clue:'the lion king'},
{category:'Movies' , clue:'scooby doo'},
{category:'Movies' , clue:'mary poppins'},
{category:'Movies' , clue:'wizard of oz'},
{category:'Movies' , clue:'superman'},
{category:'Movies' , clue:'the secret garden'},
{category:'Movies' , clue:'batman'},
{category:'Games' , clue:'ping pong'},
{category:'Thing' , clue:'snowball'},
{category:'Thing' , clue:'piano'},
{category:'Thing' , clue:'hula hoop'},
{category:'Thing' , clue:'seesaw'},
{category:'Thing' , clue:'rhinoceros'},
{category:'Games' , clue:'limbo'},
{category:'Thing' , clue:'pajamas'},
{category:'Thing' , clue:'alarm clock'},
{category:'Thing' , clue:'panguin'},
{category:'Thing' , clue:'wink'},
{category:'Characters' , clue:'darth vader'},
{category:'Characters' , clue:'spider man'},
{category:'Characters' , clue:'elsa'},
{category:'Thing' , clue:'whale'},
{category:'Thing' , clue:'hippo'},
{category:'Thing' , clue:'face'},
{category:'Thing' , clue:'ice cream cone'},
{category:'Thing' , clue:'spoon'},
{category:'Thing' , clue:'house'},
{category:'Places' , clue:'olive garden'},
{category:'TV' , clue:'once upon a time'},
{category:'Thing' , clue:'ghost'},
{category:'Action' , clue:'cooking dinner'},
{category:'Action' , clue:'ironing a shirt'},
{category:'Action' , clue:'riding a bike'},
{category:'Action' , clue:'watering the plants'},
{category:'Action' , clue:'mowing the lawn'},
{category:'Action' , clue:'building a sandcastle'},
{category:'Action' , clue:'raking leaves'},
{category:'Action' , clue:'playing chess'},
{category:'Action' , clue:'sewing clothes'},
{category:'Action' , clue:'scuba diving'},
{category:'Action' , clue:'playing four square'},
{category:'Action' , clue:'building a campfire'},
{category:'Action' , clue:'flying a kite'},
{category:'Action' , clue:'rock climbing'},
{category:'Action' , clue:'shopping at the mall'},
{category:'Action' , clue:'decorating a cupcake'},
{category:'Action' , clue:'sumo wrestling'},
{category:'Action' , clue:'picking apples'},
{category:'Action' , clue:'going trick or treat'},
{category:'Action' , clue:'digging a hole'},
{category:'Action' , clue:'petting a dog'},
{category:'Action' , clue:'watching a movie'},
{category:'Disney' , clue:'sleeping beauty'},
{category:'Disney' , clue:'snow white'},
{category:'Disney' , clue:'bambi'},
{category:'Disney' , clue:'dumbo'},
{category:'Disney' , clue:'pinocchio'},
{category:'Disney' , clue:'peter pan'},
{category:'Disney' , clue:'the jungle book'},
{category:'Disney' , clue:'the parent trap'},
{category:'Disney' , clue:'tangled'},
{category:'Disney' , clue:'winnie the pooh'},
{category:'Disney' , clue:'robin hood'},
{category:'Disney' , clue:'beauty and the beast'},
{category:'Disney' , clue:'aladdin'},
{category:'Disney' , clue:'hercules'},
{category:'Disney' , clue:'tarzan'},
{category:'Disney' , clue:'the incredibles'},
{category:'Disney' , clue:'cars'},
{category:'Disney' , clue:'brave'},
{category:'Disney' , clue:'wreck it ralph'},
{category:'Disney' , clue:'monsters inc'},
{category:'Disney' , clue:'wall e'},
{category:'Disney' , clue:'pirates of the caribbean'},
{category:'Disney' , clue:'princess and the frog'},
]

clueBank.getRandClue = function () {
  var max = this.length
  var min = 0
  randI = Math.floor(Math.random() * (max - min)) + min
  var category = this[randI].category
  var clue = this[randI].clue
  clueBank.splice(randI,1)
  return [category, clue]
}


var gifUrls = [ "https://media2.giphy.com/media/yhfTY8JL1wIAE/200.gif",
                "https://media.giphy.com/media/TlK63ED1ShqW53CCUNO/200.gif",
                "https://media1.giphy.com/media/l0NwNQ5nfmFOPvv5m/200.gif",
                "https://media3.giphy.com/media/14ayNgUBowfsjK/200.gif",
                "https://media2.giphy.com/media/HqgwFzsJncfjW/200.gif",
                "https://media1.giphy.com/media/3o8doSSp6MTgcgrnHi/200.gif",
                "https://media2.giphy.com/media/xTiTnCyfutIMgUJPgY/200.gif",
                "https://media0.giphy.com/media/5yLgocrb5JLqhq7pp3W/200.gif",
                "https://media1.giphy.com/media/CItWwfeMBdiZa/200.gif",
                "https://media3.giphy.com/media/YrJp9LFIDkwms/200.gif",
                "https://media1.giphy.com/media/XVMeBWrKBpb5m/200.gif",
                "https://media1.giphy.com/media/134DHd1VQrXvuE/200.gif",
                "https://media0.giphy.com/media/12CG3zRhS63JJu/200.gif",
                "https://media1.giphy.com/media/xT0BKKqGNmvgqvjCo0/200.gif",
                "https://media3.giphy.com/media/l41lHDSvmwnQGDUD6/200.gif",
                "https://media2.giphy.com/media/zKqY3liTpHwOc/200.gif",
                "https://media1.giphy.com/media/3oEduLs7eN545vHYYg/200.gif",
                "https://media0.giphy.com/media/xkCK3tAhDSUBa/200.gif"]

gifUrls.getUrl = function () {
  var max = this.length
  var min = 0
  randI = Math.floor(Math.random() * (max - min)) + min
  return this[randI]
}
